name: CI
on:
  push:
    branches:
      - main
    tags: ["*"]
  pull_request:
  workflow_dispatch:
concurrency:
  # Skip intermediate builds: always.
  # Cancel intermediate builds: only if it is a pull request build.
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ startsWith(github.ref, 'refs/pull/') }}
jobs:
  test:
    name: Julia ${{ matrix.version }} - ${{ matrix.os }} - ${{ matrix.arch }} - ${{ github.event_name }}
    runs-on: ${{ matrix.os }}
    timeout-minutes: 60
    permissions: # needed to allow julia-actions/cache to proactively delete old caches that it has created
      actions: write
      contents: read
    strategy:
      fail-fast: false
      matrix:
        version:
          - "1.11.5"
          - "pre"
        os:
          - ubuntu-latest
        arch:
          - x64
    steps:
      - uses: actions/checkout@v4

      # This action sets up R and AUTOMATICALLY exports R_HOME
      - name: Set up R
        id: setup-r
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: "release" # Use the latest R release

      # Install your specific R package dependency
      - name: Install R dependencies
        run: R -e 'install.packages("DataGraph")'
        shell: bash

      - uses: julia-actions/setup-julia@v2
        with:
          version: ${{ matrix.version }}
          arch: ${{ matrix.arch }}

      - name: Run tests
        uses: julia-actions/julia-runtest@v1
        env:
          R_HOME: /opt/R/4.5.1/lib/R
